- name: Rodando DSpace FrontEnd
  hosts: all
  become: yes
  gather_facts: false
  vars:
      dspace_home: "/dspace-front"

  tasks:
    - name: Rodando DSpace
      command: npx pm2 start ./dist/server/main.js
      args:
       chdir: "{{ dspace_home }}"
