- name: Instalar Certbot e configurar
  hosts: dspace_prod
  become: yes
  vars:

  tasks:
    - name: Instalando Certbot
      apt:
        name: certbot
        state: latest
        update_cache: yes

    - name: Instalando Plugin Certbot
      apt:
        name: python3-certbot-nginx
        state: latest
        update_cache: yes

