- name: Instalar Nginx
  hosts: dspace_prod
  become: yes
  vars:
    
  tasks:
    - name: Instalando nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Enviando arquivo de configuração do nginx
      template:
        src: ./dspace-nginx.j2   # caminho do template no Ansible control node
        dest: /etc/nginx/sites-available/dspace-nginx  # caminho no servidor
        mode: "0644"

    - name: Linkando arquivo
      command: ln -s /etc/nginx/sites-available/dspace-nginx /etc/nginx/sites-enabled/
      ignore_errors: yes

    - name: Reiniciando Nginx
      command: systemctl reload nginx
