- name:  Configura e roda o Solr usando daemons
  hosts: dspace_prod
  become: yes
  vars:
    solr_user: "solr"
    solr_group: "solr"

  tasks:
   - name: Enviando solr.service para o destino
     copy:
       src: "{{ home }}/daemons/solr.service"
       dest: /etc/systemd/system/solr.service

   - name: Reiniciando o systemcd
     command: systemctl daemon-reexec

   - name: Inicializando solr
     systemd:
       name: solr
       enabled: yes
       state: started
