- name: Instalar Apache Ant via apt
  hosts: dspace_prod
  become: yes

  tasks:
    - name: Atualizar cache do apt e instalar Ant
      apt:
        name: ant
        state: present
        update_cache: yes
        force: yes
        install_recommends: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
