- name: Instalando PostgreSQL no servidor
  hosts: all
  become: yes
  vars:
    postgresql_version: "16"
  tasks:
    - name: Atualizando cache de pacotes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalando dependências para adicionar repositório
      apt:
        name: 
          - gnupg
          - wget
          - ca-certificates
        state: present

    - name: Adicionando repositório oficial do PostgreSQL
      shell: |
        echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/pgdg.gpg
      args:
        creates: /etc/apt/sources.list.d/pgdg.list

    - name: Atualizando cache de pacotes após adicionar repositório
      apt:
        update_cache: yes

    - name: Instalando PostgreSQL {{ postgresql_version }} e cliente correspondente
      apt:
        name:
          - "postgresql-{{ postgresql_version }}"
          - "postgresql-client-{{ postgresql_version }}"
          - "postgresql-common"
        state: present

    - name: Garantir que o serviço PostgreSQL está ativo e habilitado
      service:
        name: postgresql
        state: started
        enabled: yes
