- name: Instalando DSpace
  hosts: all
  become: yes
  vars:

  tasks:

    - name: Copiar dspace.service para o destino
      copy:
        src: ./dspace.service
        dest: /etc/systemd/system/dspace.service
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Recarregar systemd
      systemd:
        daemon_reload: yes

    - name: Habilitar e iniciar o DSpace
      systemd:
        name: dspace
        enabled: yes
        state: started
